name: chatcrm
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  dotenv: ^3.0.0
  get_it: ^7.1.3
  grpc: ^3.0.0
